knp_paginator:
  template:
    pagination: '@KnpPaginator/Pagination/bootstrap_v5_pagination.html.twig'     # sliding pagination controls template
    sortable: '@KnpPaginator/Pagination/bootstrap_v5_fa_sortable_link.html.twig' # sort link template
    filtration: '@KnpPaginator/Pagination/bootstrap_v5_filtration.html.twig'  # filters template